<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <AssemblyName>Yuma.Persistence.Abstractions.Tests</AssemblyName>
      <RootNamespace>Yuma</RootNamespace>
      <Description>Yuma's Distributed Application Libraries: Unit Tests for Basic Persistence Abstractions.</Description>
      <IsPackable>false</IsPackable>
   </PropertyGroup>

   <ItemGroup>
      <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
   </ItemGroup>

   <ItemGroup>
      <ProjectReference Include="..\Yuma.Persistence.Abstractions\Yuma.Persistence.Abstractions.csproj"/>
   </ItemGroup>

   <ItemGroup>
      <PackageReference Include="AutoFixture"/>
      <PackageReference Include="AutoFixture.AutoMoq"/>
      <PackageReference Include="AutoFixture.Xunit2"/>
      <PackageReference Include="coverlet.collector"/>
      <PackageReference Include="FluentAssertions"/>
      <PackageReference Include="Microsoft.NET.Test.Sdk"/>
      <PackageReference Include="Moq"/>
      <PackageReference Include="xunit"/>
      <PackageReference Include="xunit.analyzers"/>
      <PackageReference Include="xunit.runner.visualstudio"/>
   </ItemGroup>

</Project>
